import os

# Create the .streamlit directory if it doesn't exist
if not os.path.exists('.streamlit'):
    os.makedirs('.streamlit')

# Write the secrets.toml file
# IMPORTANT: Replace 'YOUR_ACTUAL_GROQ_API_KEY' with your real Groq API key
secrets_content = """
MYNAME = "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"
"""

with open('.streamlit/secrets.toml', 'w') as f:
    f.write(secrets_content)

print("Created .streamlit/secrets.toml with a placeholder for the MYNAME secret.")
print("IMPORTANT: Please edit the .streamlit/secrets.toml file and replace 'YOUR_ACTUAL_GROQ_API_KEY' with your actual Groq API key.")
